const page=await figma.getNodeByIdAsync('0:1'); await figma.setCurrentPageAsync(page);
if(page.findOne(n=>n.type==='COMPONENT_SET'&&n.name==='Showcase / Document row'))throw new Error('Showcases already exist. Use repair-layout.js and the saved state ledger to resume without duplication.');
await Promise.all([{family:'Manrope',style:'Regular'},{family:'Manrope',style:'Medium'},{family:'Manrope',style:'SemiBold'},{family:'IBM Plex Mono',style:'Regular'}].map(f=>figma.loadFontAsync(f)));
const created=[], sets={}, exports=[], previewIds=[];
const allVars=await figma.variables.getLocalVariablesAsync();
const collections=await figma.variables.getLocalVariableCollectionsAsync();
const themeVars={};for(const theme of ['light','dark']){const c=collections.find(c=>c.name===`HB · ${theme==='light'?'Light':'Dark'}`); themeVars[theme]=Object.fromEntries(allVars.filter(v=>v.variableCollectionId===c.id).map(v=>[v.name.replace('color/',''),v]));}
const space=Object.fromEntries(allVars.filter(v=>v.variableCollectionId===collections.find(c=>c.name==='HB · Geometry').id).map(v=>[v.name,v]));
const styles=Object.fromEntries((await figma.getLocalTextStylesAsync()).map(s=>[s.name.replace('HB / ',''),s]));
const track=n=>{created.push(n.id);return n};
function paint(theme,key,opacity=1){return {...figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:0,g:0,b:0}},'color',themeVars[theme][key]),opacity};}
function rect(parent,name,x,y,w,h,theme,key='border',opacity=1){const n=track(figma.createRectangle());n.name=name;n.resize(w,h);n.x=x;n.y=y;n.fills=[paint(theme,key,opacity)];parent.appendChild(n);return n;}
function text(parent,label,theme,style='UI/Small',color='text'){const n=track(figma.createText());n.name=label;n.fontName=styles[style].fontName;n.textStyleId=styles[style].id;n.characters=label;n.fills=[paint(theme,color)];parent.appendChild(n);return n;}
function stack(parent,name,w,theme,direction='VERTICAL',gap=16,padding=0){const n=track(figma.createAutoLayout(direction));n.name=name;n.fills=[];n.resize(w,10);n.primaryAxisSizingMode='AUTO';n.counterAxisSizingMode='FIXED';n.clipsContent=false;parent.appendChild(n);n.itemSpacing=gap;n.setBoundVariable('itemSpacing',space[`spacing/${gap}`]||null);for(const side of ['Top','Right','Bottom','Left']){n[`padding${side}`]=padding;if(padding)n.setBoundVariable(`padding${side}`,space[`spacing/${padding}`]);}return n;}
function panel(parent,name,x,y,w,h,theme){const n=track(figma.createFrame());n.name=name;n.resize(w,h);n.x=x;n.y=y;n.fills=[paint(theme,'bg')];n.strokes=[paint(theme,'border')];n.strokeWeight=1;n.setBoundVariable('cornerRadius',space['radius/sm']);n.clipsContent=true;parent.appendChild(n);return n;}
function at(n,x,y){n.x=x;n.y=y;return n;}
function inline(parent,name,w,theme){const n=stack(parent,name,w,theme,'HORIZONTAL',8);n.counterAxisAlignItems='CENTER';n.primaryAxisAlignItems='SPACE_BETWEEN';return n;}
function title(parent,label,theme,mobile=false){return text(parent,label,theme,mobile?'UI/Mobile heading':'UI/Heading');}
function mono(parent,label,theme,mobile=false,color='text-muted'){return text(parent,label,theme,mobile?'UI/Mobile mono':'UI/Mono',color);}
function rule(parent,y,w,theme){rect(parent,'Divider',0,y,w,1,theme,'border');}
function signature(parent,x,y,w,theme){const svg=track(figma.createNodeFromSvg('<svg width="220" height="60" viewBox="0 0 220 60" xmlns="http://www.w3.org/2000/svg"><path d="M8 43C26 8 28 3 20 44C45 12 51 12 38 39C57 26 40 48 70 34C85 25 89 23 79 39C90 25 99 22 96 38L112 31C105 48 120 41 137 28C154 15 166 21 147 35L198 28M42 49L213 40" fill="none" stroke="#73736a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'));parent.appendChild(svg);svg.rescale(w/220);svg.x=x;svg.y=y;svg.findAll(n=>n.type==='VECTOR').forEach(n=>{n.strokes=[paint(theme,'text-muted')];});return svg;}
function qr(parent,x,y,size,theme){const q=track(figma.createFrame());q.name='Capture QR · sample';q.resize(size,size);q.x=x;q.y=y;q.fills=[paint(theme,'bg')];parent.appendChild(q);const cell=size/21;function finder(ox,oy){for(let y=0;y<7;y++)for(let x=0;x<7;x++)if(x===0||x===6||y===0||y===6||(x>=2&&x<=4&&y>=2&&y<=4))rect(q,'QR module',(ox+x)*cell,(oy+y)*cell,cell,cell,theme,'text');}finder(0,0);finder(14,0);finder(0,14);for(let y=0;y<21;y++)for(let x=0;x<21;x++){if((x<8&&y<8)||(x>12&&y<8)||(x<8&&y>12))continue;if(((x*17+y*31+x*y*3)%11)<5)rect(q,'QR module',x*cell,y*cell,cell,cell,theme,'text');}return q;}
// Repeated rows are true components, with editable text properties.
const rowVariants={}, applicantVariants={};
for(const theme of ['light','dark']){
 for(const size of ['Desktop','Mobile']){
  const mobile=size==='Mobile';const w=mobile?472:340;const c=track(figma.createComponent());c.name=`Theme=${theme}, Size=${size}`;c.resize(w,mobile?52:40);c.fills=[];c.layoutMode='HORIZONTAL';c.primaryAxisSizingMode='FIXED';c.counterAxisSizingMode='FIXED';c.primaryAxisAlignItems='SPACE_BETWEEN';c.counterAxisAlignItems='CENTER';c.itemSpacing=16;c.setBoundVariable('itemSpacing',space['spacing/16']);
  const name=text(c,'Photo ID',theme,mobile?'UI/Mobile body':'UI/Small');const state=mono(c,'Received',theme,mobile,'text-muted');
  rowVariants[`${theme}/${size}`]=c;
 }
 for(const status of ['Missing','Collected']){
  const c=track(figma.createComponent());c.name=`Theme=${theme}, Status=${status}`;c.resize(336,150);c.fills=[paint(theme,'bg')];c.strokes=[paint(theme,'border')];c.strokeWeight=1;c.setBoundVariable('cornerRadius',space['radius/sm']);c.layoutMode='VERTICAL';c.primaryAxisSizingMode='FIXED';c.counterAxisSizingMode='FIXED';c.itemSpacing=12;c.setBoundVariable('itemSpacing',space['spacing/12']);for(const s of ['Top','Bottom','Left','Right'])c.setBoundVariable(`padding${s}`,space['spacing/16']);
  const head=inline(c,'Applicant and state',304,theme);text(head,status==='Missing'?'Ahmed Dubois':'Wei Smith',theme,'UI/Body');
  const dot=track(figma.createEllipse());dot.resize(6,6);dot.fills=[paint(theme,status==='Missing'?'accent':'text-faint')];head.appendChild(dot);
  mono(c,status==='Missing'?'Unit 488 · Summerhill':'Unit 898 · Cedar Plaza',theme);
  text(c,status==='Missing'?'4 documents missing':'All documents collected',theme,'UI/Small',status==='Missing'?'accent':'text-muted');
  applicantVariants[`${theme}/${status}`]=c;
 }
}
const rowSet=track(figma.combineAsVariants(Object.values(rowVariants),page));rowSet.name='Showcase / Document row';rowSet.description='Editable document status row. Desktop / Mobile sizes; exact portfolio light / dark colors. Used as instances in capture and upload panels.';rowSet.x=80;rowSet.y=80;
const labelKey=rowSet.addComponentProperty('Label','TEXT','Photo ID');const statusKey=rowSet.addComponentProperty('Status label','TEXT','Received');
rowSet.children.forEach((v,i)=>{v.x=24+(i%2)*520;v.y=24+Math.floor(i/2)*90;v.children[0].componentPropertyReferences={characters:labelKey};v.children[1].componentPropertyReferences={characters:statusKey};});rowSet.resize(1080,230);sets.documentRow=rowSet.id;
const appSet=track(figma.combineAsVariants(Object.values(applicantVariants),page));appSet.name='Showcase / Applicant';appSet.description='Applicant tracking card based on the original DocChaser Applications screen. Theme and document-state variants. All copy remains editable.';appSet.x=80;appSet.y=380;appSet.children.forEach((v,i)=>{v.x=24+(i%2)*360;v.y=24+Math.floor(i/2)*180;});appSet.resize(760,390);sets.applicant=appSet.id;
function docrow(parent,label,status,theme,mobile=false,w){const c=rowVariants[`${theme}/${mobile?'Mobile':'Desktop'}`];const i=track(c.createInstance());parent.appendChild(i);if(w)i.resize(w,i.height);i.setProperties({[labelKey]:label,[statusKey]:status});return i;}
function applicant(parent,theme,status,x,y,w=336){const i=track(applicantVariants[`${theme}/${status}`].createInstance());parent.appendChild(i);i.x=x;i.y=y;i.resize(w,150);return i;}
function capture(parent,x,y,theme,mobile=false){const w=mobile?160:224;const c=panel(parent,'QR capture',x,y,w,mobile?152:226,theme);const s=at(stack(c,'Capture content',w-32,theme,'VERTICAL',12),16,16);mono(s,'Capture link',theme,mobile);qr(s,0,0,mobile?76:94,theme);if(!mobile)text(s,'Scan to continue',theme,'UI/Small','text-muted');return c;}
function docDesktop(content,theme){const p=panel(content,'Applications dashboard',48,40,800,390,theme);const h=at(inline(p,'Dashboard header',744,theme),28,24);title(h,'Applications',theme);mono(h,'+ New case',theme,false,'accent');rule(p,78,800,theme);applicant(p,theme,'Missing',28,102,356);applicant(p,theme,'Collected',404,102,368);const faded=applicant(p,theme,'Missing',28,270,356);faded.opacity=.38;const faded2=applicant(p,theme,'Collected',404,270,368);faded2.opacity=.28;
 capture(content,670,276,theme);const u=panel(content,'Documents and signature',88,330,448,170,theme);const s=at(stack(u,'Collected documents',400,theme,'VERTICAL',4),24,18);docrow(s,'Photo ID','Received',theme,false,400);docrow(s,'Signature','Signed',theme,false,400);signature(u,135,100,260,theme);}
function docMobile(content,theme){const p=panel(content,'Applicant documents',24,24,552,430,theme);const s=at(stack(p,'Applicant collection',488,theme,'VERTICAL',16),32,24);mono(s,'Applications / Applicant 1',theme,true);title(s,'Wei Smith',theme,true);const line=track(figma.createRectangle());line.resize(488,1);line.fills=[paint(theme,'border')];s.appendChild(line);docrow(s,'Photo ID','Received',theme,true,488);docrow(s,'Signature','Signed',theme,true,488);const sign=at(stack(p,'Signature field',280,theme,'VERTICAL',8),32,260);signature(sign,0,0,280,theme);mono(sign,'All collected',theme,true,'accent');capture(content,412,310,theme,true);}
function candidate(parent,theme,x,y,w,name,detail){const p=panel(parent,'Candidate card',x,y,w,166,theme);const s=at(stack(p,'Candidate details',w-40,theme,'VERTICAL',12),20,20);text(s,name,theme,'UI/Body');text(s,detail,theme,'UI/Small','text-muted');mono(s,'View simulation',theme,false,'accent');return p;}
function recruiterDesktop(content,theme){const p=panel(content,'Candidate profiling board',40,40,838,402,theme);const h=at(inline(p,'Board header',782,theme),28,24);title(h,'Candidate profiling board',theme);mono(h,'2 candidates',theme);rule(p,78,838,theme);at(mono(p,'Unsorted',theme),28,104);at(mono(p,'Schedule interview',theme),426,104);candidate(p,theme,28,144,370,'Jordan Lee','Expansion account manager');candidate(p,theme,426,144,382,'Marcus Vance','Senior growth manager');const q=panel(content,'First-year simulation',302,310,606,192,theme);const s=at(stack(q,'Simulation details',558,theme,'VERTICAL',12),24,20);mono(s,'Marcus Vance / First year',theme,false,'accent');const time=inline(s,'Periods',558,theme);['Month 1–3','Month 4–6','Month 7–12'].forEach(t=>mono(time,t,theme));text(s,'Systems ramp → Team leadership → EMEA expansion',theme,'UI/Small','text-muted');const l=rect(q,'Time axis',24,150,558,1,theme,'border');rect(q,'Active period',24,149,150,3,theme,'accent');}
function recruiterMobile(content,theme){const p=panel(content,'Candidate simulation',24,24,552,430,theme);const s=at(stack(p,'First-year profile',488,theme,'VERTICAL',16),32,28);mono(s,'Candidate profiling',theme,true);title(s,'Marcus Vance',theme,true);text(s,'Senior growth manager',theme,'UI/Mobile body','text-muted');rect(p,'Time axis',32,174,488,1,theme,'border');rect(p,'Active period',32,173,146,3,theme,'accent');at(mono(p,'Month 1–3',theme,true,'accent'),32,194);at(text(p,'Systems ramp',theme,'UI/Mobile heading'),32,238);at(text(p,'Salesforce + Tableau',theme,'UI/Mobile body','text-muted'),32,288);const f=panel(content,'Interview action',280,364,296,84,theme);at(mono(f,'Schedule interview',theme,true,'accent'),24,26);}
const before='894717b93c3d684ccd52f4f15344f7fefbd37613',after='461a0d7694462e6f5bc16a6d7df3dad11ff0ea3b';
function photo(parent,name,x,y,w,h,hash){const r=track(figma.createRectangle());r.name=name;r.resize(w,h);r.x=x;r.y=y;r.fills=[{type:'IMAGE',imageHash:hash,scaleMode:'FILL'}];parent.appendChild(r);return r;}
function pipelineDesktop(content,theme){const p=panel(content,'Photo editing workspace',44,40,832,418,theme);const h=at(inline(p,'Workspace header',776,theme),28,22);title(h,'Photo review',theme);mono(h,'Ready for listing',theme,false,'accent');rule(p,76,832,theme);photo(p,'Original apartment photo',24,98,382,254,before);photo(p,'Edited apartment photo',426,98,382,254,after);at(mono(p,'Original',theme),24,366);at(mono(p,'Edited',theme,false,'accent'),426,366);const f=panel(content,'Batch progress',550,402,354,94,theme);const s=at(stack(f,'Pipeline status',310,theme,'VERTICAL',8),22,15);mono(s,'Original → Edit → Review',theme);rect(f,'Progress track',22,60,310,2,theme,'border');rect(f,'Review complete',22,60,310,2,theme,'accent');}
function pipelineMobile(content,theme){const p=panel(content,'Edited apartment preview',24,24,552,430,theme);photo(p,'Edited apartment photo',20,20,512,300,after);const s=at(inline(p,'Photo review status',488,theme),32,342);text(s,'Edited',theme,'UI/Mobile heading');mono(s,'Reviewed',theme,true,'accent');const f=panel(content,'Original preview',48,228,176,152,theme);photo(f,'Original apartment photo',8,8,160,106,before);at(mono(f,'Original',theme),12,119);}
function sqlDesktop(content,theme){const p=panel(content,'Question and query workspace',48,48,824,396,theme);const s=at(stack(p,'Question and SQL',768,theme,'VERTICAL',24),28,28);mono(s,'Question',theme,false,'accent');title(s,'Which buildings have a 1 bedroom under $1,600?',theme);const q=stack(s,'Verifiable query',768,theme,'VERTICAL',16,24);q.fills=[paint(theme,'surface')];mono(q,'SQL / buildings',theme);text(q,'SELECT name, price_1bed\nFROM buildings\nWHERE price_1bed < 1600;',theme,'UI/Mono');const f=panel(content,'Checkable answer',430,378,468,116,theme);const fs=at(stack(f,'Answer details',420,theme,'VERTICAL',8),24,20);mono(fs,'Source query visible',theme,false,'accent');text(fs,'A checkable answer from real data.',theme,'UI/Body');}
function sqlMobile(content,theme){const p=panel(content,'Question and SQL',24,24,552,430,theme);const s=at(stack(p,'Query content',488,theme,'VERTICAL',24),32,28);mono(s,'Question',theme,true,'accent');const t=title(s,'1 bedroom under $1,600?',theme,true);t.textAutoResize='HEIGHT';t.resize(488,t.height);const q=stack(s,'Source query',488,theme,'VERTICAL',16,16);q.fills=[paint(theme,'surface')];text(q,'SELECT name, price_1bed\nFROM buildings\nWHERE price_1bed < 1600;',theme,'UI/Mobile mono');mono(s,'Source query visible',theme,true,'accent');}
const projects=[['docchaser',docDesktop,docMobile],['recruiterai',recruiterDesktop,recruiterMobile],['listing-photo-pipeline',pipelineDesktop,pipelineMobile],['asksql',sqlDesktop,sqlMobile]];
for(let pi=0;pi<projects.length;pi++){
 const [slug,desktop,mobile]=projects[pi];if(page.findOne(n=>n.type==='COMPONENT_SET'&&n.name===`Showcase / ${slug}`))throw new Error('Existing composition: resume with its ledger');const variants=[];
 for(const theme of ['light','dark'])for(const format of ['desktop','mobile']){
  const w=format==='desktop'?960:600,h=format==='desktop'?540:480;
  const comp=track(figma.createComponent());comp.name=`Theme=${theme}, Format=${format}`;comp.description='Editable editorial product composition. No device frame or promotional title. Transparent edge mask blends into the actual webpage background.';comp.resize(w,h);comp.fills=[];comp.clipsContent=true;
  const mask=rect(comp,'Edge fade · alpha mask',0,0,w,h,theme,'bg');mask.fills=[{type:'GRADIENT_LINEAR',gradientTransform:[[0,1,0],[-1,0,1]],gradientStops:[{position:0,color:{r:1,g:1,b:1,a:0}},{position:.045,color:{r:1,g:1,b:1,a:1}},{position:.91,color:{r:1,g:1,b:1,a:1}},{position:1,color:{r:1,g:1,b:1,a:0}}]}];mask.isMask=true;mask.maskType='ALPHA';
  const content=track(figma.createFrame());content.name='Product surfaces';content.resize(w,h);content.fills=[];comp.appendChild(content);(format==='desktop'?desktop:mobile)(content,theme);variants.push(comp);
 }
 const set=track(figma.combineAsVariants(variants,page));set.name=`Showcase / ${slug}`;set.description='Reusable project showcase: independently composed Desktop 16:9 and Mobile 5:4, each in the portfolio light/dark palette. Source UI simplified for presentation; not a product redesign. Alpha fades allow the exported visual to merge with any site surface.';set.x=1320;set.y=80+pi*1240;set.fills=[];
 variants.forEach((c,i)=>{c.x=i%2===0?24:1032;c.y=i<2?24:610;});set.resize(1660,1190);sets[slug]=set.id;
 for(let i=0;i<variants.length;i++){
  const c=variants[i],theme=i<2?'light':'dark',format=i%2===0?'desktop':'mobile';
  const review=track(figma.createFrame());review.name=`Preview / ${slug} / ${format} / ${theme}`;review.resize(c.width,c.height);review.fills=[paint(theme,'surface')];review.x=3200+(format==='mobile'?1040:0);review.y=80+pi*1240+(theme==='dark'?610:0);review.clipsContent=true;page.appendChild(review);
  const ins=track(c.createInstance());review.appendChild(ins);ins.x=0;ins.y=0;ins.name=`${slug}-${format}-${theme}`;ins.exportSettings=[{format:'PNG',constraint:{type:'SCALE',value:2},colorProfile:'SRGB'}];exports.push({slug,format,theme,nodeId:ins.id,previewId:review.id,w:ins.width,h:ins.height});previewIds.push(review.id);
 }
}
return {createdNodeIds:created,componentSets:sets,exports,previewIds,counts:{sets:Object.keys(sets).length,variants:24,compositions:exports.length,editableText:page.findAllWithCriteria({types:['TEXT']}).length,instances:page.findAllWithCriteria({types:['INSTANCE']}).length},fontFamilies:[...new Set(page.findAllWithCriteria({types:['TEXT']}).map(n=>n.fontName.family))]};
